// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package hermitboard_api

import (
	"github.com/chenningg/hermitboard-api/pulid"
)

type DeleteConnectionInput struct {
	ID pulid.PULID `json:"id"`
}
