// Code generated by ent, DO NOT EDIT.

package asset

import (
	"time"

	"github.com/chenningg/hermitboard-api/ent/schema/pulid"
)

const (
	// Label holds the string label denoting the asset type in the database.
	Label = "asset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldAssetClassID holds the string denoting the asset_class_id field in the database.
	FieldAssetClassID = "asset_class_id"
	// EdgeAssetClass holds the string denoting the asset_class edge name in mutations.
	EdgeAssetClass = "asset_class"
	// EdgeCryptocurrency holds the string denoting the cryptocurrency edge name in mutations.
	EdgeCryptocurrency = "cryptocurrency"
	// EdgeTransactionBase holds the string denoting the transaction_base edge name in mutations.
	EdgeTransactionBase = "transaction_base"
	// EdgeTransactionQuote holds the string denoting the transaction_quote edge name in mutations.
	EdgeTransactionQuote = "transaction_quote"
	// EdgeDailyAssetPrice holds the string denoting the daily_asset_price edge name in mutations.
	EdgeDailyAssetPrice = "daily_asset_price"
	// Table holds the table name of the asset in the database.
	Table = "assets"
	// AssetClassTable is the table that holds the asset_class relation/edge.
	AssetClassTable = "assets"
	// AssetClassInverseTable is the table name for the AssetClass entity.
	// It exists in this package in order to avoid circular dependency with the "assetclass" package.
	AssetClassInverseTable = "asset_classes"
	// AssetClassColumn is the table column denoting the asset_class relation/edge.
	AssetClassColumn = "asset_class_id"
	// CryptocurrencyTable is the table that holds the cryptocurrency relation/edge.
	CryptocurrencyTable = "cryptocurrencies"
	// CryptocurrencyInverseTable is the table name for the Cryptocurrency entity.
	// It exists in this package in order to avoid circular dependency with the "cryptocurrency" package.
	CryptocurrencyInverseTable = "cryptocurrencies"
	// CryptocurrencyColumn is the table column denoting the cryptocurrency relation/edge.
	CryptocurrencyColumn = "asset_id"
	// TransactionBaseTable is the table that holds the transaction_base relation/edge.
	TransactionBaseTable = "transactions"
	// TransactionBaseInverseTable is the table name for the Transaction entity.
	// It exists in this package in order to avoid circular dependency with the "transaction" package.
	TransactionBaseInverseTable = "transactions"
	// TransactionBaseColumn is the table column denoting the transaction_base relation/edge.
	TransactionBaseColumn = "base_asset_id"
	// TransactionQuoteTable is the table that holds the transaction_quote relation/edge.
	TransactionQuoteTable = "transactions"
	// TransactionQuoteInverseTable is the table name for the Transaction entity.
	// It exists in this package in order to avoid circular dependency with the "transaction" package.
	TransactionQuoteInverseTable = "transactions"
	// TransactionQuoteColumn is the table column denoting the transaction_quote relation/edge.
	TransactionQuoteColumn = "quote_asset_id"
	// DailyAssetPriceTable is the table that holds the daily_asset_price relation/edge.
	DailyAssetPriceTable = "daily_asset_prices"
	// DailyAssetPriceInverseTable is the table name for the DailyAssetPrice entity.
	// It exists in this package in order to avoid circular dependency with the "dailyassetprice" package.
	DailyAssetPriceInverseTable = "daily_asset_prices"
	// DailyAssetPriceColumn is the table column denoting the daily_asset_price relation/edge.
	DailyAssetPriceColumn = "base_asset_id"
)

// Columns holds all SQL columns for asset fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldAssetClassID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UpdateDefaultDeletedAt holds the default value on update for the "deleted_at" field.
	UpdateDefaultDeletedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() pulid.PULID
)
