// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID       string `json:"id"`
	AuthID   string `json:"authId"`
	Nickname string `json:"nickname"`
	Email    bool   `json:"email"`
}

type DeleteAccount struct {
	ID string `json:"id"`
}

type NewAccount struct {
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateAccount struct {
	ID       string  `json:"id"`
	Nickname *string `json:"nickname"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
}
