// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chenningg/hermitboard-api/ent/asset"
	"github.com/chenningg/hermitboard-api/ent/blockchain"
	"github.com/chenningg/hermitboard-api/ent/cryptocurrency"
	"github.com/chenningg/hermitboard-api/ent/predicate"
	"github.com/chenningg/hermitboard-api/pulid"
)

// CryptocurrencyQuery is the builder for querying Cryptocurrency entities.
type CryptocurrencyQuery struct {
	config
	limit                *int
	offset               *int
	unique               *bool
	order                []OrderFunc
	fields               []string
	predicates           []predicate.Cryptocurrency
	withAsset            *AssetQuery
	withBlockchains      *BlockchainQuery
	modifiers            []func(*sql.Selector)
	loadTotal            []func(context.Context, []*Cryptocurrency) error
	withNamedBlockchains map[string]*BlockchainQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CryptocurrencyQuery builder.
func (cq *CryptocurrencyQuery) Where(ps ...predicate.Cryptocurrency) *CryptocurrencyQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit adds a limit step to the query.
func (cq *CryptocurrencyQuery) Limit(limit int) *CryptocurrencyQuery {
	cq.limit = &limit
	return cq
}

// Offset adds an offset step to the query.
func (cq *CryptocurrencyQuery) Offset(offset int) *CryptocurrencyQuery {
	cq.offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CryptocurrencyQuery) Unique(unique bool) *CryptocurrencyQuery {
	cq.unique = &unique
	return cq
}

// Order adds an order step to the query.
func (cq *CryptocurrencyQuery) Order(o ...OrderFunc) *CryptocurrencyQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryAsset chains the current query on the "asset" edge.
func (cq *CryptocurrencyQuery) QueryAsset() *AssetQuery {
	query := &AssetQuery{config: cq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cryptocurrency.Table, cryptocurrency.FieldID, selector),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, cryptocurrency.AssetTable, cryptocurrency.AssetColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBlockchains chains the current query on the "blockchains" edge.
func (cq *CryptocurrencyQuery) QueryBlockchains() *BlockchainQuery {
	query := &BlockchainQuery{config: cq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cryptocurrency.Table, cryptocurrency.FieldID, selector),
			sqlgraph.To(blockchain.Table, blockchain.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, cryptocurrency.BlockchainsTable, cryptocurrency.BlockchainsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Cryptocurrency entity from the query.
// Returns a *NotFoundError when no Cryptocurrency was found.
func (cq *CryptocurrencyQuery) First(ctx context.Context) (*Cryptocurrency, error) {
	nodes, err := cq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cryptocurrency.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CryptocurrencyQuery) FirstX(ctx context.Context) *Cryptocurrency {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Cryptocurrency ID from the query.
// Returns a *NotFoundError when no Cryptocurrency ID was found.
func (cq *CryptocurrencyQuery) FirstID(ctx context.Context) (id pulid.PULID, err error) {
	var ids []pulid.PULID
	if ids, err = cq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cryptocurrency.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CryptocurrencyQuery) FirstIDX(ctx context.Context) pulid.PULID {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Cryptocurrency entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Cryptocurrency entity is found.
// Returns a *NotFoundError when no Cryptocurrency entities are found.
func (cq *CryptocurrencyQuery) Only(ctx context.Context) (*Cryptocurrency, error) {
	nodes, err := cq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cryptocurrency.Label}
	default:
		return nil, &NotSingularError{cryptocurrency.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CryptocurrencyQuery) OnlyX(ctx context.Context) *Cryptocurrency {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Cryptocurrency ID in the query.
// Returns a *NotSingularError when more than one Cryptocurrency ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CryptocurrencyQuery) OnlyID(ctx context.Context) (id pulid.PULID, err error) {
	var ids []pulid.PULID
	if ids, err = cq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cryptocurrency.Label}
	default:
		err = &NotSingularError{cryptocurrency.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CryptocurrencyQuery) OnlyIDX(ctx context.Context) pulid.PULID {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Cryptocurrencies.
func (cq *CryptocurrencyQuery) All(ctx context.Context) ([]*Cryptocurrency, error) {
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return cq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (cq *CryptocurrencyQuery) AllX(ctx context.Context) []*Cryptocurrency {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Cryptocurrency IDs.
func (cq *CryptocurrencyQuery) IDs(ctx context.Context) ([]pulid.PULID, error) {
	var ids []pulid.PULID
	if err := cq.Select(cryptocurrency.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CryptocurrencyQuery) IDsX(ctx context.Context) []pulid.PULID {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CryptocurrencyQuery) Count(ctx context.Context) (int, error) {
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return cq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CryptocurrencyQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CryptocurrencyQuery) Exist(ctx context.Context) (bool, error) {
	if err := cq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return cq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CryptocurrencyQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CryptocurrencyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CryptocurrencyQuery) Clone() *CryptocurrencyQuery {
	if cq == nil {
		return nil
	}
	return &CryptocurrencyQuery{
		config:          cq.config,
		limit:           cq.limit,
		offset:          cq.offset,
		order:           append([]OrderFunc{}, cq.order...),
		predicates:      append([]predicate.Cryptocurrency{}, cq.predicates...),
		withAsset:       cq.withAsset.Clone(),
		withBlockchains: cq.withBlockchains.Clone(),
		// clone intermediate query.
		sql:    cq.sql.Clone(),
		path:   cq.path,
		unique: cq.unique,
	}
}

// WithAsset tells the query-builder to eager-load the nodes that are connected to
// the "asset" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CryptocurrencyQuery) WithAsset(opts ...func(*AssetQuery)) *CryptocurrencyQuery {
	query := &AssetQuery{config: cq.config}
	for _, opt := range opts {
		opt(query)
	}
	cq.withAsset = query
	return cq
}

// WithBlockchains tells the query-builder to eager-load the nodes that are connected to
// the "blockchains" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CryptocurrencyQuery) WithBlockchains(opts ...func(*BlockchainQuery)) *CryptocurrencyQuery {
	query := &BlockchainQuery{config: cq.config}
	for _, opt := range opts {
		opt(query)
	}
	cq.withBlockchains = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Cryptocurrency.Query().
//		GroupBy(cryptocurrency.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CryptocurrencyQuery) GroupBy(field string, fields ...string) *CryptocurrencyGroupBy {
	grbuild := &CryptocurrencyGroupBy{config: cq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return cq.sqlQuery(ctx), nil
	}
	grbuild.label = cryptocurrency.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty"`
//	}
//
//	client.Cryptocurrency.Query().
//		Select(cryptocurrency.FieldCreatedAt).
//		Scan(ctx, &v)
func (cq *CryptocurrencyQuery) Select(fields ...string) *CryptocurrencySelect {
	cq.fields = append(cq.fields, fields...)
	selbuild := &CryptocurrencySelect{CryptocurrencyQuery: cq}
	selbuild.label = cryptocurrency.Label
	selbuild.flds, selbuild.scan = &cq.fields, selbuild.Scan
	return selbuild
}

func (cq *CryptocurrencyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range cq.fields {
		if !cryptocurrency.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CryptocurrencyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Cryptocurrency, error) {
	var (
		nodes       = []*Cryptocurrency{}
		_spec       = cq.querySpec()
		loadedTypes = [2]bool{
			cq.withAsset != nil,
			cq.withBlockchains != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Cryptocurrency).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Cryptocurrency{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(cq.modifiers) > 0 {
		_spec.Modifiers = cq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withAsset; query != nil {
		if err := cq.loadAsset(ctx, query, nodes, nil,
			func(n *Cryptocurrency, e *Asset) { n.Edges.Asset = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withBlockchains; query != nil {
		if err := cq.loadBlockchains(ctx, query, nodes,
			func(n *Cryptocurrency) { n.Edges.Blockchains = []*Blockchain{} },
			func(n *Cryptocurrency, e *Blockchain) { n.Edges.Blockchains = append(n.Edges.Blockchains, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range cq.withNamedBlockchains {
		if err := cq.loadBlockchains(ctx, query, nodes,
			func(n *Cryptocurrency) { n.appendNamedBlockchains(name) },
			func(n *Cryptocurrency, e *Blockchain) { n.appendNamedBlockchains(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range cq.loadTotal {
		if err := cq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CryptocurrencyQuery) loadAsset(ctx context.Context, query *AssetQuery, nodes []*Cryptocurrency, init func(*Cryptocurrency), assign func(*Cryptocurrency, *Asset)) error {
	ids := make([]pulid.PULID, 0, len(nodes))
	nodeids := make(map[pulid.PULID][]*Cryptocurrency)
	for i := range nodes {
		fk := nodes[i].AssetID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(asset.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "asset_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *CryptocurrencyQuery) loadBlockchains(ctx context.Context, query *BlockchainQuery, nodes []*Cryptocurrency, init func(*Cryptocurrency), assign func(*Cryptocurrency, *Blockchain)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[pulid.PULID]*Cryptocurrency)
	nids := make(map[pulid.PULID]map[*Cryptocurrency]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(cryptocurrency.BlockchainsTable)
		s.Join(joinT).On(s.C(blockchain.FieldID), joinT.C(cryptocurrency.BlockchainsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(cryptocurrency.BlockchainsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(cryptocurrency.BlockchainsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(pulid.PULID)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := *values[0].(*pulid.PULID)
			inValue := *values[1].(*pulid.PULID)
			if nids[inValue] == nil {
				nids[inValue] = map[*Cryptocurrency]struct{}{byID[outValue]: struct{}{}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "blockchains" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (cq *CryptocurrencyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	if len(cq.modifiers) > 0 {
		_spec.Modifiers = cq.modifiers
	}
	_spec.Node.Columns = cq.fields
	if len(cq.fields) > 0 {
		_spec.Unique = cq.unique != nil && *cq.unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CryptocurrencyQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (cq *CryptocurrencyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   cryptocurrency.Table,
			Columns: cryptocurrency.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: cryptocurrency.FieldID,
			},
		},
		From:   cq.sql,
		Unique: true,
	}
	if unique := cq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := cq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cryptocurrency.FieldID)
		for i := range fields {
			if fields[i] != cryptocurrency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CryptocurrencyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(cryptocurrency.Table)
	columns := cq.fields
	if len(columns) == 0 {
		columns = cryptocurrency.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.unique != nil && *cq.unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedBlockchains tells the query-builder to eager-load the nodes that are connected to the "blockchains"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (cq *CryptocurrencyQuery) WithNamedBlockchains(name string, opts ...func(*BlockchainQuery)) *CryptocurrencyQuery {
	query := &BlockchainQuery{config: cq.config}
	for _, opt := range opts {
		opt(query)
	}
	if cq.withNamedBlockchains == nil {
		cq.withNamedBlockchains = make(map[string]*BlockchainQuery)
	}
	cq.withNamedBlockchains[name] = query
	return cq
}

// CryptocurrencyGroupBy is the group-by builder for Cryptocurrency entities.
type CryptocurrencyGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CryptocurrencyGroupBy) Aggregate(fns ...AggregateFunc) *CryptocurrencyGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the group-by query and scans the result into the given value.
func (cgb *CryptocurrencyGroupBy) Scan(ctx context.Context, v any) error {
	query, err := cgb.path(ctx)
	if err != nil {
		return err
	}
	cgb.sql = query
	return cgb.sqlScan(ctx, v)
}

func (cgb *CryptocurrencyGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range cgb.fields {
		if !cryptocurrency.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cgb *CryptocurrencyGroupBy) sqlQuery() *sql.Selector {
	selector := cgb.sql.Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cgb.fields)+len(cgb.fns))
		for _, f := range cgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cgb.fields...)...)
}

// CryptocurrencySelect is the builder for selecting fields of Cryptocurrency entities.
type CryptocurrencySelect struct {
	*CryptocurrencyQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CryptocurrencySelect) Scan(ctx context.Context, v any) error {
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	cs.sql = cs.CryptocurrencyQuery.sqlQuery(ctx)
	return cs.sqlScan(ctx, v)
}

func (cs *CryptocurrencySelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := cs.sql.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
