// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chenningg/hermitboard-api/ent/source"
	"github.com/chenningg/hermitboard-api/ent/sourcetype"
	"github.com/chenningg/hermitboard-api/pulid"
)

// SourceTypeCreate is the builder for creating a SourceType entity.
type SourceTypeCreate struct {
	config
	mutation *SourceTypeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (stc *SourceTypeCreate) SetCreatedAt(t time.Time) *SourceTypeCreate {
	stc.mutation.SetCreatedAt(t)
	return stc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (stc *SourceTypeCreate) SetNillableCreatedAt(t *time.Time) *SourceTypeCreate {
	if t != nil {
		stc.SetCreatedAt(*t)
	}
	return stc
}

// SetUpdatedAt sets the "updated_at" field.
func (stc *SourceTypeCreate) SetUpdatedAt(t time.Time) *SourceTypeCreate {
	stc.mutation.SetUpdatedAt(t)
	return stc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (stc *SourceTypeCreate) SetNillableUpdatedAt(t *time.Time) *SourceTypeCreate {
	if t != nil {
		stc.SetUpdatedAt(*t)
	}
	return stc
}

// SetDeletedAt sets the "deleted_at" field.
func (stc *SourceTypeCreate) SetDeletedAt(t time.Time) *SourceTypeCreate {
	stc.mutation.SetDeletedAt(t)
	return stc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (stc *SourceTypeCreate) SetNillableDeletedAt(t *time.Time) *SourceTypeCreate {
	if t != nil {
		stc.SetDeletedAt(*t)
	}
	return stc
}

// SetValue sets the "value" field.
func (stc *SourceTypeCreate) SetValue(s sourcetype.Value) *SourceTypeCreate {
	stc.mutation.SetValue(s)
	return stc
}

// SetDescription sets the "description" field.
func (stc *SourceTypeCreate) SetDescription(s string) *SourceTypeCreate {
	stc.mutation.SetDescription(s)
	return stc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (stc *SourceTypeCreate) SetNillableDescription(s *string) *SourceTypeCreate {
	if s != nil {
		stc.SetDescription(*s)
	}
	return stc
}

// SetID sets the "id" field.
func (stc *SourceTypeCreate) SetID(pu pulid.PULID) *SourceTypeCreate {
	stc.mutation.SetID(pu)
	return stc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (stc *SourceTypeCreate) SetNillableID(pu *pulid.PULID) *SourceTypeCreate {
	if pu != nil {
		stc.SetID(*pu)
	}
	return stc
}

// AddSourceIDs adds the "sources" edge to the Source entity by IDs.
func (stc *SourceTypeCreate) AddSourceIDs(ids ...pulid.PULID) *SourceTypeCreate {
	stc.mutation.AddSourceIDs(ids...)
	return stc
}

// AddSources adds the "sources" edges to the Source entity.
func (stc *SourceTypeCreate) AddSources(s ...*Source) *SourceTypeCreate {
	ids := make([]pulid.PULID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return stc.AddSourceIDs(ids...)
}

// Mutation returns the SourceTypeMutation object of the builder.
func (stc *SourceTypeCreate) Mutation() *SourceTypeMutation {
	return stc.mutation
}

// Save creates the SourceType in the database.
func (stc *SourceTypeCreate) Save(ctx context.Context) (*SourceType, error) {
	var (
		err  error
		node *SourceType
	)
	stc.defaults()
	if len(stc.hooks) == 0 {
		if err = stc.check(); err != nil {
			return nil, err
		}
		node, err = stc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SourceTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = stc.check(); err != nil {
				return nil, err
			}
			stc.mutation = mutation
			if node, err = stc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(stc.hooks) - 1; i >= 0; i-- {
			if stc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = stc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, stc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*SourceType)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SourceTypeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (stc *SourceTypeCreate) SaveX(ctx context.Context) *SourceType {
	v, err := stc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (stc *SourceTypeCreate) Exec(ctx context.Context) error {
	_, err := stc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stc *SourceTypeCreate) ExecX(ctx context.Context) {
	if err := stc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (stc *SourceTypeCreate) defaults() {
	if _, ok := stc.mutation.CreatedAt(); !ok {
		v := sourcetype.DefaultCreatedAt()
		stc.mutation.SetCreatedAt(v)
	}
	if _, ok := stc.mutation.UpdatedAt(); !ok {
		v := sourcetype.DefaultUpdatedAt()
		stc.mutation.SetUpdatedAt(v)
	}
	if _, ok := stc.mutation.ID(); !ok {
		v := sourcetype.DefaultID()
		stc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (stc *SourceTypeCreate) check() error {
	if _, ok := stc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SourceType.created_at"`)}
	}
	if _, ok := stc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SourceType.updated_at"`)}
	}
	if _, ok := stc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "SourceType.value"`)}
	}
	if v, ok := stc.mutation.Value(); ok {
		if err := sourcetype.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "SourceType.value": %w`, err)}
		}
	}
	if v, ok := stc.mutation.Description(); ok {
		if err := sourcetype.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SourceType.description": %w`, err)}
		}
	}
	return nil
}

func (stc *SourceTypeCreate) sqlSave(ctx context.Context) (*SourceType, error) {
	_node, _spec := stc.createSpec()
	if err := sqlgraph.CreateNode(ctx, stc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*pulid.PULID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (stc *SourceTypeCreate) createSpec() (*SourceType, *sqlgraph.CreateSpec) {
	var (
		_node = &SourceType{config: stc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: sourcetype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: sourcetype.FieldID,
			},
		}
	)
	if id, ok := stc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := stc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sourcetype.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := stc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sourcetype.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := stc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sourcetype.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	if value, ok := stc.mutation.Value(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: sourcetype.FieldValue,
		})
		_node.Value = value
	}
	if value, ok := stc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sourcetype.FieldDescription,
		})
		_node.Description = &value
	}
	if nodes := stc.mutation.SourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourcetype.SourcesTable,
			Columns: []string{sourcetype.SourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: source.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SourceTypeCreateBulk is the builder for creating many SourceType entities in bulk.
type SourceTypeCreateBulk struct {
	config
	builders []*SourceTypeCreate
}

// Save creates the SourceType entities in the database.
func (stcb *SourceTypeCreateBulk) Save(ctx context.Context) ([]*SourceType, error) {
	specs := make([]*sqlgraph.CreateSpec, len(stcb.builders))
	nodes := make([]*SourceType, len(stcb.builders))
	mutators := make([]Mutator, len(stcb.builders))
	for i := range stcb.builders {
		func(i int, root context.Context) {
			builder := stcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, stcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, stcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, stcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (stcb *SourceTypeCreateBulk) SaveX(ctx context.Context) []*SourceType {
	v, err := stcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (stcb *SourceTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := stcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stcb *SourceTypeCreateBulk) ExecX(ctx context.Context) {
	if err := stcb.Exec(ctx); err != nil {
		panic(err)
	}
}
